# Generated by Django 4.0.4 on 2022-06-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_manager_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='manager_mail',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
